[project]
name = "construction-cost-estimate-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.93.1",
    "openai-agents>=0.1.0",
    "python-dotenv>=1.1.1",
]
