from pydantic import BaseModel, Field
from typing import List, Optional

class ValidationWarning(BaseModel):
    """
    An individual warning or error message generated by the validation engine.
    """
    warning_code: str = Field(..., description="Machine-readable code for the warning type.")
    message: str = Field(..., description="Human-readable explanation of the validation result.")

class ValidationSummary(BaseModel):
    """
    High-level overview of which validation categories passed or failed.
    """
    area_valid: bool = Field(..., description="True if total used area is within usable limits.")
    density_valid: bool = Field(..., description="True if room density is architecturally sound.")
    dimension_valid: bool = Field(..., description="True if all room dimensions meet architectural standards.")
    utilization_valid: bool = Field(..., description="True if space utilization is within reasonable bounds.")

class ValidationResponse(BaseModel):
    """
    The complete response from the architectural validation engine.
    """
    success: bool = Field(..., description="Indicates if the plan is generally valid for construction.")
    plot_area: float = Field(..., description="Total calculated plot area (length * width).")
    usable_area: float = Field(..., description="Net usable area after efficiency deductions.")
    total_used_area: float = Field(..., description="Sum of all assigned room areas.")
    remaining_area: float = Field(..., description="Unassigned area remaining for circulation and services.")
    utilization_ratio: float = Field(..., description="Ratio of used area to usable area.")
    warnings: List[ValidationWarning] = Field(default_factory=list, description="List of intelligent warnings and errors.")
    validation_summary: ValidationSummary = Field(..., description="Summary of validation statuses.")
    message: Optional[str] = Field(None, description="A high-level message summarizing the validation result.")
